### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by DanBmh** [Picovoice/speech-to-intent-benchmark#11]
1. How many sample utterances did you use to train rhino, 432 or 50?

2. Do you have results for Watson trained with 50 sample utterances?

3. Could you please add a graph in the readme with benchmarks comparisons with only 50 instead of 432 examples?
I've seen you did them already for Dialogflow (https://picovoice.ai/tutorials/benchmarking-rhino-against-dialogflow/) and Lex (https://picovoice.ai/tutorials/benchmarking-rhino-against-amazon-lex/) but I can't find the exact values to redraw the graphs. 
I think they are better for real world performance estimations, because only very few people will write over four-hundred example intents ...

**Comment by kenarsa** [comment]
1- 432
2- We don't but feel free to create it yourself.
3- not a priority for us at this point but if you add it happy to do a PR. when doing that you prob want to do multiple subsets and provide mean and std of results.

Thanks!
