### ISSUE TITLE
calculate the wer

### ISSUE THREAD

**Issue by tekkkon** [Picovoice/speech-to-intent-benchmark#14]
while diving deep to understand how each platform performs in terms of speech and nlu, I found some gaps in text form between asr output and nlu expected slot values

is there a way to calculate the word error rate to do analysis at component level? i did not find the ground truth transcript in the label.json

thanks

**Comment by kenarsa** [comment]
The goal of benchmark is to measure end-to-end performance which is what matters to customers/users. Some engines (like Rhino) don't even have a separate STT component so such comparison can be futile in this context. More info here https://picovoice.ai/blog/end-to-end-intent-inference-from-speech/

**Comment by tekkkon** [comment]
thanks @kenarsa 
yes, i tried rhino with end to end speech to intent, which is pretty awesome
in the same time, i am doing deeper debugging for analyzing other platform's component level performance 
wondering if you guys can share the ground truth transcript for the current dataset? this can help community to gain deeper insights about all these major platforms. i can contribute to put together a wer calculation in a pr if you guys can share the ground truth transcript

**Comment by tekkkon** [comment]
@kenarsa what is your thought about the [previous message ](https://github.com/Picovoice/speech-to-intent-benchmark/issues/14#issuecomment-673620576) ? thanks

**Comment by mehrdadfeller** [comment]
@tekkkon WER is not the right metric for NLU and not something we can compare here since Rhino does not provide and work on text output. We are working on a new benchmark release for Speech-to-Text where we measure WER on established datasets and several STT solutions (including Microsoft, IBM, Amazon, Google, etc).

**Comment by tekkkon** [comment]
Thanks for the information @mehrdadfeller .
The new benchmark to measure WER among all other platforms sounds great, do you have a rough timeline about this project? Let me know if I can help.

**Comment by mehrdadfeller** [comment]
@tekkkon can you please drop me an email at mehrdad@picovoice.ai to discuss what you'd like to accomplish. thanks!
