### ISSUE TITLE
Some more benchmark results

### ISSUE THREAD

**Issue by DanBmh** [Picovoice/speech-to-intent-benchmark#9]
Thanks for your project. I did use it to run a few more benchmarks with other projects:

![compare_barrista](https://user-images.githubusercontent.com/18572490/86830600-2bc24200-c096-11ea-91ec-713420480961.png)

You can find the complete benchmarking code here: https://gitlab.com/Jaco-Assistant/Benchmark-Jaco

**Comment by kenarsa** [comment]
Thanks! If you can do this in a way that is reproducible we will be interested in a PR and possibly merge into mainline. Your lex results are very different from what we have so it would be good to figure that out first. Snips benchmark is tricky cause you need the piece of HW and II guess the console is not open to public anymore? How did you manage to create ASR without console?

**Comment by DanBmh** [comment]
You should be able to reproduce everything with the code I linked above. It also has the install instructions for the different projects.

The Alexa results are similar to your lex_50 run here: https://picovoice.ai/tutorials/benchmarking-rhino-against-amazon-lex/
I also used only 50 sample intents, because at the time I started this, the dialogflow export only had those 50 examples.

Could you add the comparison images of the two different trainset sizes with dialogflow and lex in this repo too?

I did run the snips benchmark on a raspi were I already had a working snips installation. The console access might be a problem, but I still could use mine after contacting the snips support because I need it for an university project too.

**Comment by kenarsa** [comment]
got it. makes sense. The 50 training example for lex is available here: https://picovoice.ai/tutorials/benchmarking-rhino-against-amazon-lex/

**Comment by mehrdadfeller** [comment]
This is Mehrdad with Picovoice; Thanks for sharing these results with us. Great work indeed! I am in charge of our benchmarking efforts and would love to chat with you when you have a moment. Can you please share your contact info with me or perhaps shoot me an email me to mehrdad@picovoice.ai?

**Comment by DanBmh** [comment]
In case you have overlooked my e-mail, I did resend it again.
